# --<{   Even Fibonacci numbers  }>--
# --<{ Coded by Parker Cranfield }>--
# --<{       July 26, 2020       }>--

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# PRO TIP - REMEMBER HOW I MADE FIB SEQUENCE - COULD COME IN HANDY

fib_lst = []
even_fib = []
a = 0
b = 1
while a <= 4_000_000:
    fib_lst.append(a)
    c = a + b
    a = b
    b = c

print(fib_lst)

for i in fib_lst:
    if i % 2 == 0:
        even_fib.append(i)

print(even_fib)

print(sum(even_fib))
