# --<{  Highly divisible triangular number  }>--
# --<{      Coded by Parker Cranfield       }>--
# --<{           August 19, 2020            }>--

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt

most_fac_atm = 0
num = 1
num_of_factors = set()

while len(num_of_factors) <= 500:
    num_of_factors.clear()
    triangle_num = int(num*(num+1)/2)
    for n in range(1, int(sqrt(triangle_num))+1):
        if triangle_num % n == 0 and n not in num_of_factors:
            hold = triangle_num
            triangle_num = triangle_num/n
            num_of_factors.add(n)
            num_of_factors.add(triangle_num)
            triangle_num = hold

    if len(num_of_factors) > most_fac_atm:
        most_fac_atm = len(num_of_factors)
        print(f"{triangle_num} | {most_fac_atm} | {num}", end="\r", flush=True) # REMEMBER THIS

    num += 1
print(f"{triangle_num} | {most_fac_atm} | {num}")